# Generated by Django 5.2.5 on 2025-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=2000)),
                ('tipo', models.CharField(max_length=50)),
                ('prazo', models.DateTimeField(auto_now_add=True)),
                ('atualizar', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
