# Generated by Django 5.2.5 on 2025-09-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='prazo',
            new_name='data_criado',
        ),
    ]
