# Generated by Django 5.2.5 on 2025-09-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_prazo_tarefas_data_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
